version: '3.8'

services:
  api:
    image: ai-product-description-generator:latest
    build:
      context: ../..
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - WOOCOMMERCE_API_KEY=${WOOCOMMERCE_API_KEY}
      - SALLA_API_KEY=${SALLA_API_KEY}
      - ZED_API_KEY=${ZED_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge